name: Update Synthetic tests

description: Updates synthetic tests
inputs:
  is-pr-workflow:
    description: Is this action on a PR workflow
    required: false
    default: 'false'
  pulumi-stack:
    description: The Pulumi stack to use
    required: true
  pulumi-access-token:
    description: The Pulumi access token to use
    required: true
  datadog-app-key:
    description: The DataDog app key to use
    required: true
  datadog-api-key:
    description: The DataDog api key to use
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install deps (with cache)
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --no-progress --ignore-scripts
        working-directory: synthetic-tests

    - name: Setup Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2

    - name: Update Synthetic Tests
      shell: bash
      env:
        IS_PR_WORKFLOW: ${{ inputs.is-pr-workflow }}
        PULUMI_STACK: ${{ inputs.pulumi-stack }}
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi-access-token }}
        DATADOG_APP_KEY: ${{ inputs.datadog-app-key }}
        DATADOG_API_KEY: ${{ inputs.datadog-api-key }}
      run: make update-synthetic-tests
