name: Update Synthetic tests

description: Updates synthetic tests
inputs:
  is-pr-workflow:
    description: Is this action on a PR workflow
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install deps (with cache)
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --no-progress --ignore-scripts
        working-directory: synthetic-tests

    - name: Setup Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2

    - name: Update Synthetic Tests
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        PULUMI_STACK: synthetic-tests/prod
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        IS_PR_WORKFLOW: ${{ inputs.is-pr-workflow }}
      run: make update-synthetic-tests
