version: '3.9'

services:
  app:
    image: send-securely:latest
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    command: [ '--https-port', '8443' ]
