name: Pull Request
on:
  pull_request:
    branches: [master]
jobs:
  verify:
    name: Acceptance Test
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Send Securely Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-app-cache
          key: ${{ runner.os }}-buildx-app-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-app-

      - name: Build Send Securely Docker image (with cache)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: |
            send-securely
            send-securely:${{ github.sha }}
            send-securely:latest
          cache-from: type=local,src=/tmp/.buildx-app-cache
          cache-to: type=local,dest=/tmp/.buildx-app-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-app-cache
          mv /tmp/.buildx-app-cache-new /tmp/.buildx-app-cache

      - name: Cache Cypress binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --no-progress --ignore-scripts
        env:
          CYPRESS_INSTALL_BINARY: 0

      # Install and check Cypress binary
      - run: yarn run cypress install
      - run: yarn run cypress cache list

      - name: Verify Acceptance tests
        run: make verify
        env:
          SKIP_BUILD: 1 # we already built the image, should just run it instead

      - name: Stop services
        if: always()
        run: make stop-docker

  view-synthetic-test-diff:
    runs-on: ubuntu-latest
    env:
      CI: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Synthetic Tests
        uses: ./.github/composite/update-synthetic-tests
        with:
          is-pr-workflow: true
          pulumi-stack: synthetic-tests/prod
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
