name: Pull Request
on:
  pull_request:
    branches: [master]
jobs:
  verify:
    name: Acceptance Test
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --no-progress --ignore-scripts
#        env:
#          CYPRESS_INSTALL_BINARY: 0

      - name: Verify Acceptance tests
        run: make verify

      - name: Stop services
        if: always()
        run: make stop-docker
