name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  view-synthetic-test-diff:
    runs-on: ubuntu-latest
    env:
      CI: 1

    steps:
      - name: Update Synthetic Tests
        uses: ./.github/actions/update-synthetic-tests
        with:
          is-pr-workflow: true
