name: Update Synthetic Tests

on:
  push:
    branches: [master]

jobs:
  update-synthetic-tests:
    runs-on: ubuntu-latest
    env:
      CI: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Synthetic Tests
        uses: ./.github/actions/update-synthetic-tests
