name: Update Synthetic Tests

on:
  push:
    branches: [master]

jobs:
  update-synthetic-tests:
    runs-on: ubuntu-latest
    env:
      CI: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Synthetic Tests
        uses: ./.github/composite/update-synthetic-tests
        with:
          pulumi-stack: synthetic-tests/prod
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
